import pytest
def func(i):
	return i
def test_func():
	print('test jenkins')
	assert func(3)==3
def test_func2():
	print('test jenkins')
	assert func(6)==6
def test_func3():
	print('test jenkins')
	assert func(5)==5